### ISSUE TITLE
Outputs blank image

### ISSUE THREAD

**Issue by lavakalas** [Gustash/Hyprshot#3]
Hello, I'm using hyprland with arch linux and trying to take screenshot with 
`hyprshot -m output -f screen.png`

but it results in saving a blank image and outputs
`convert: geometry does not contain image '/home/katana/screen.png' @ warning/attribute.c/GetImageBoundingBox/554.`

**Comment by lavakalas** [comment]
also simple `grim` returns black image like this one
![20230406_19h06m24s_grim](https://user-images.githubusercontent.com/42173474/230452594-c236d4c4-76f2-4c45-ad06-b7e914496f77.png)

**Comment by niraami** [comment]
@lavakalas If you discover what the source of the issue is, please let me know - a bunch of applications started returning a black screen and I'm unsure what caused it. wayland? hyprland? wlroots?
Some of them, I haven't tested before the ones I knew worked have stopped working, like OBS and Discord - so it might still be grim.

**Comment by PassiHD2004** [comment]
are you using nvidia? because if yes, install `hyprland-nvidia-hidpi-git`. This fully fixed it for me.

**Comment by niraami** [comment]
Actually [`hyprland-nvidia-git`](https://aur.archlinux.org/packages/hyprland-nvidia-git) was enough for me, I got it working a few days ago finally... fixed a few other issues as well. I guess it's not quite true that it only fixes "flickers" as some sites would suggest.

**Comment by PassiHD2004** [comment]
for whatever reason screenshotting broke again.... from what ive seen, the patches are currently not being properly maintained, could also be something else tho

**Comment by Gustash** [comment]
I use AMD so I don't know how to debug Nvidia issues. Either way, this script uses general commands like grim, slurp, etc.

It appears this issue is only present on Nvidia cards, as I've had no reports from any AMD users and it's working correctly on my end. Since Nvidia is known to have lacking support for Wayland, I'm going to assume it's not an issue with this package.

Feel free to open another issue if you're an AMD/Intel user and you get this same problem.
